### ISSUE TITLE
Documentation for Table fields missing

### ISSUE THREAD

**Issue by Chartman123** [DocuWare/Validation-WebAPI-Sample#1]
Please provide some documentation regarding the new Table fields (available since DocuWare 7.1).

I've tested it on our test system and the provided JSON from DocuWare to the Web service looks like this:

```
{
	"FieldName": "POSITIONEN",
	"ItemElementName": "Table",
	"Item": {
		"Row": [
			{
				"ColumnValue": [
					{
						"FieldName": "POSIT_NR",
						"ItemElementName": "Decimal",
						"Item": "1"
					},
					{
						"FieldName": "POSIT_BEZEICHNUNG",
						"ItemElementName": "String",
						"Item": "asdf"
					},
					{
						"FieldName": "POSIT_BETRAG",
						"ItemElementName": "Decimal",
						"Item": "1234.00"
					},
					{
						"FieldName": "POSIT_DATUM",
						"ItemElementName": "Date",
						"Item": "2019-11-27T00:00:00Z"
					}
				]
			}
		]
	}
}
```

**Comment by DWDoP** [comment]
@Chartman123 we have examples for table fields [here](https://developer.docuware.com/dotNet_CodeExamples/workWithTableFields.html).
Does this help or do you need more information?

**Comment by Chartman123** [comment]
For us, it's fine, I just thought about some other costumers who start programming with the API. I think it would be nice to add the documentation also here as for the other field types.
